### ISSUE TITLE
Misleading ~lincent output

### ISSUE THREAD

**Issue by debuos512** [SamStudio8/dbot-stats#132]
In the service of perspicacity and in the interests of being persnickety, I've noticed that the given ~lincent output may be incorrect in regards to differing timestamps for the instigation of recording.

For example, 

'reality is responsible for 1.49% (2,063) messages in #oaosidl since Sat, 25th May 2013'

I assume this is actually 1.49% of the total channel lines whose recording began Tue, 22nd January 2013 (unless you've already made provision for this, but 1.49% seems awfully low).

**Comment by SamStudio8** [comment]
Yes your assumption is correct, I suppose it could be weighted for how long
you've been in the channel for but that is outside the interests of the
command.

The number is low as I suspect there is a bug in either stats or users that
has otherwise melted your data.

**Comment by SamStudio8** [comment]
@reality I think weighting things will cause too much overhead (as we'd have to have a way of calculating how many lines have occurred in a channel from a specific timestamp as opposed to just a day of the week etc.) for something that is relatively trivial. 

In which case, I think I'll just drop the "since" part of the string as I expect that using the channel timestamp (which would be correct) would cause confusion with users who'd complain "I wasn't even in the channel at that date!"
