### ISSUE TITLE
Count nick changes

### ISSUE THREAD

**Issue by Flickwire** [SamStudio8/dbot-stats#24]
Keep a count or list of previous nicks of users, potentially with a most indecisive / most constant user

**Comment by SamStudio8** [comment]
@reality I imagine we can just keep track of the number of aliases a user has in knownUsers? Although I think I would prefer to add a field to the userStats and chanStats that is incremented inside the fixStats?

**Comment by debuos512** [comment]
This data is already there. We just need to iterate through knownUsers.server.aliases and count how many aliases each parent user has. 

Up to you if you want to store this as a count, it may become difficult when manual fixing is involved.

**Comment by SamStudio8** [comment]
I just wanted the stats data to be centralized as I don't like the idea of pulling data in from various modules as that could make resolving users to their data more messy in future (as various modules and such make data available). Unless for this case we consider the proposed command should be inserted in the users module rather than stats?

**Comment by debuos512** [comment]
Well this is something that belongs to stats really but it's okay for it to depend on the knownUser data being there, it already does for tracking

**Comment by SamStudio8** [comment]
True, I was just thinking about making the data easily available via the web interface or a future API module that it might be easier to just serve stats that are inside userStats and chanStats rather than pulling data from various sources.

Stats currently only relies on knownUsers to resolve usernames, rather than actually using the data.
