### ISSUE TITLE
Seven day rolling data points

### ISSUE THREAD

**Issue by SamStudio8** [SamStudio8/dbot-stats#63]
Implement a circular array to test how rolling data points could be deployed.

@reality, with regard to rolling datapoints, would it be better to;
- Add timers to the module to trigger a function that updates "pointers" to now use the next slot in the circular array, or
- Compare the timestamp in each event and determine the array element it should be applied to?

**Comment by SamStudio8** [comment]
@reality, I've just thought that timers won't work anyway as they'll be reset when the bot is restarted - they aren't actually "fixed" to a time. They just countdown?

**Comment by debuos512** [comment]
As discussed it would be a pain in the arse to do this with timers, as you've got the problem of reloading / restarting modules so I figure you'd end up having to do the working out a fair bit anyway, as you're correct you pass them an 'in x MS execute this function' rather than a time.

**Comment by debuos512** [comment]
However depending on how difficult the other approach would be, I doubt it would be too hard to abstract away some of the difficulty in using timers by adding some features to timer.js (https://github.com/reality/depressionbot/blob/master/timer.js) to allow:
- Persistent timers
- Timers which execute at a given time rather than at a countdown

We could even make timer.js into a DBot module and use the hook system to execute the persistent timers!

**Comment by SamStudio8** [comment]
@reality This would be a much more elegant solution as otherwise we'd have to compare every event's timestamp to the timestamp of the stats field and determine whether a week has passed by checking for a difference of over 6.048e+8 and then updating the field or something.

**Comment by SamStudio8** [comment]
Test seems to be stable, closing as complete.
